#!/bin/bash

function get_marketing_version {

  xcconfig_file="$1"

  if [[ -f "$xcconfig_file" ]]; then

    local result
    result="$(grep 'MARKETING_VERSION' "$xcconfig_file" | awk '{print $3}' )"
    echo "$result"
  else
    echo "Could not find $xcconfig_file"
    exit 10
}

function create_gh_release {
  tag_name="$1"
  repo_url="$2"
  post_body="{\"tag_name\":\"$tag_name\",\"name\":\"$tag_name\",\"generate_release_notes\":true}"
  curl -X POST "${repo_url}/releases" \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GH_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -d "$post_body"
}


## main

version=$(get_marketing_version "Reveri/Config/Common.xcconfig")

create_gh_release "$version" "https://api.github.com/repos/mikelrob/release_test" # "https://api.github.com/repos/reveri-health/reveri-ios"
