name: Make a Release
on:
  push:
    branches:
      - 'master'

jobs:
  make_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Github Release
        run: ${{ github.workspace }}/scripts/make_gh_release
